export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const SUBMIT_SURVEY_SUCCESS = "SUBMIT_SURVEY_SUCCESS";
export const SUBMIT_SURVEY_FAIL = "SUBMIT_SURVEY_FAIL";
export const FETCH_SURVEYS = "FETCH_SURVEYS";
